export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Larry",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Big Daniel",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alejandra S",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Juan Jose E",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Luis Ayala",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Prof. Jasmin",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Diego Urbano",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Liliana",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "HEY, Tu front funciona.",
    photo: "assets/post/1.jpeg",
    date: "Hace 5 minutos",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "Hace 15 minutos",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Esta es otra prueba de que Funciona.",
    photo: "assets/post/3.jpeg",
    date: "Hace 1 Hora",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "Hace 4 Horas",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "Hace 5 Horas",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "Hace 1 Día",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Saludos.",
    photo: "assets/post/7.jpeg",
    date: "Hace 2 Días",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "Hace 3 Días",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "HOlA.",
    photo: "assets/post/9.jpeg",
    date: "Hace 5 Días",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "Hace 1 Semana",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
